### ISSUE TITLE
Roadmap for FAT tuning

### ISSUE THREAD

**Issue by mfld-fr** [ghaerr/elks#327]
Things are getting messy with 3 (very) active contributors on the same features and still some confusion or disagreement on the final FAT or boot design. So it is worth to agree on a roadmap to conclude and to keep everybody happy with the project:

- [x] create a staging branch 'fat_tune' (`master` now reserved for bug fixes and release 0.3.1): DONE
- [x] add 32-bit inode in configuration menu: DONE in 9350dd05674d2411c7c0d9aca2cadb7deb1ccc54
- [x] tune `setboot` to preserve existing extended FAT BPB (as described in https://github.com/elks-org/elks/pull/325#discussion_r377739122): DONE in a0007756958fc41d4d5d76484b49d38e07e5dec3
- [x] add FAT image case to `image/Makefile` : DONE in 60092a7af7d3ba54c1fa6030cda674e35bb664ea
- [ ] tune `setboot` to update ELKS BPB (geometry and payload as 2 different options)
- [ ] move FAT payload out of boot sector to relax space constraint
- [ ] always include ELKS BPB in boot sector: almost done in 7ac93835a3fbd437e9973d8b6542ed6258f681f1
- [ ] create a new `boot` file with the existing FAT payload
- [ ] add `boot` installation to package manager
- [ ] check 'HRS' FAT attributes for `boot` (as explained in https://github.com/elks-org/elks/issues/296#issuecomment-584208943)
- [ ] drop the FAT BPB duplication in payload
- [ ] extract FAT location of `boot` with `mtools` (`awk` is your friend, see https://github.com/elks-org/elks/issues/296#issuecomment-583873256)
- [ ] add generic payload location in ELKS BPB
- [ ] option : convert FAT payload in `boot` from ASM to C
- [ ] option: improve `boot` to handle `linux` fragmentation
- [ ] option: honor MBR parameters in boot sector (passed by MBR code)
- [ ] tune the CI to rename `fd1440.bin` to `fd1440-minix.bin`
- [ ] tune the CI to generate `fd1440-fat.bin`
- [ ] option: add non-regression testing for EMU86 in CI
- [ ] merge `fat_tune` into `master` and release (0.3.2 ?)

**Comment by tkchia** [comment]
Hello @mfld-fr, hello @ghaerr,

Thank you.  Am I correct that this is a road map for the longer term?

From what I see, this is the current situation:
  * For Minix FS, we have a 512-byte boot sector, which loads a 512-byte Minix-specific loader, which loads `/linux` and splits it into its "setup" and "kernel" portions.
  * Likewise for FAT, except that the 512-byte boot sector tries to directly load and split `/linux` itself --- with some restrictions on where it can be on disk.  But perhaps we might want or need to extend the bootloader to two sectors.
  * `/linux` contains, in its first 512 bytes, a largely unused "bootloader" which we only use to determine how to split the rest of `/linux` into "setup" and "kernel" parts.  (The "bootloader" seems to be largely a holdover from [The Boot Protocol](https://www.kernel.org/doc/html/latest/x86/boot.html) used for Linux for x86-32/-64.  It _can_ _potentially_ be used to make the Linux or ELKS kernel itself a bootable image, but it seems modern Linux/x86-64 kernels no longer even allow this --- and I am not sure how essential this is to ELKS.)

I am thinking that, inside all of this, there should be opportunities to reduce the complexity of the whole boot setup.

Thank you!

**Comment by ghaerr** [comment]
@mfld-fr : Good idea for this roadmap, I assume you'll keep it up by editing it for all to see as issues are debated and code written? It is time for more discussion before more code is needed.

I assume this Roadmap is for 0.3.2 in branch fat_tune, with master for 0.3.1 with no more boot sector changes?

Shall we comment/question/clarify on various roadmap entries in this thread?

@tkchia: what is the free space left on the current FAT boot sector (with EPB in)?

**Comment by mfld-fr** [comment]
Yes, you are both right, this is a roadmap for the v0.3.2 release, so after the upcoming v0.3.1.

About the 'raw' boot sector that is the first of the 'linux' image :
1. it is still used today to boot from a 'raw' image without any file system (see #299)
2. after loading, it is used as the `INITSEG` to store some kernel initial parameters

I already started to empty that storage with a cleanup of the unused parameters (see the recent history of `setup.S`). As soon as `INITSEG` is empty, we can remove that first sector and use the 'generic' one instead.

**Comment by ghaerr** [comment]
I have a design and can write an update for `setboot` that addresses most of the setboot issues in the roadmap, as well as fixes the bug in 0.3.1 that the fd360-fat.bin and fd720-fat.bin images are broken and won't boot.

Would you like to discuss it, or should I just submit a PR for the master branch to fix 0.3.1?

Changes to `setboot` resulting from roadmap decisions to boot blocks or only for 0.3.2 features would be easily made at the time boot blocks change in 0.3.2, of course.

**Comment by mfld-fr** [comment]
PR is a good place to review and discuss some proposed changes, this is how GitHub designed the workflow.

**Comment by tkchia** [comment]
Hello @ghaerr,

> @tkchia: what is the free space left on the current FAT boot sector (with EPB in)?

That will be about ... 20 bytes.
```
000001c0  83 89 ec 5d c2 02 00 45  4c 4b 53 20 62 6f 6f 74  |...]...ELKS boot|
000001d0  0d 0a 00 21 0d 0a 00 50  72 65 73 73 20 6b 65 79  |...!...Press key|
000001e0  0d 0a 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
                   ^^ ^^ ^^ ^^ ^^  ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^
000001f0  00 00 00 00 00 00 00 00  04 3f 10 04 65 4c 55 aa  |.........?..eLU.|
          ^^ ^^ ^^ ^^ ^^ ^^ ^^
```

**Comment by mfld-fr** [comment]
We are obviously back to a rolling version, not worth to spend any more time in planning and road mapping activities. So closing this one.
