### ISSUE TITLE
[busyelks] Integrate into main configuration & build

### ISSUE THREAD

**Issue by mfld-fr** [ghaerr/elks#349]
Today the `busyelks` is a side sub-project that has been recently reworked by Marcin in #310 and #336, but stills not integrated into the main configuration & build.

- [x] move that part into the `elkscmd` folder : DONE in #379 
- [x] insert it into the main configuration : DONE in #379, defect #386, fix #389
- [x] insert it into the main build : DONE in #379
- [x] tune the `ino_t` print format as in #347 : DONE in 647ab5d087020fe6edc27467bf33d4fd9806080a

**Comment by mfld-fr** [comment]
Almost done - except one defect in configuration to be fixed in #386

**Comment by mfld-fr** [comment]
Remaining defect #386 fixed in #389
